defmodule Athanor.Repo.Migrations.AddCancelDrainDeadline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:jobs) do
      add :cancel_drain_deadline_at, :utc_datetime_usec
    end

    create index(:jobs, [:cancel_drain_deadline_at],
             name: "jobs_canceled_drain_deadline_idx",
             where: "state = 'canceled' AND cancel_drain_deadline_at IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:jobs, [:cancel_drain_deadline_at],
                     name: "jobs_canceled_drain_deadline_idx"
                   )

    alter table(:jobs) do
      remove :cancel_drain_deadline_at
    end
  end
end
