defmodule Athanor.Repo.Migrations.AddQueuedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:jobs) do
      add :queued_at, :utc_datetime_usec
    end
  end

  def down do
    alter table(:jobs) do
      remove :queued_at
    end
  end
end
