defmodule Athanor.Repo.Migrations.AddBootDeadlineAndAttempts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:jobs) do
      add :boot_deadline_at, :utc_datetime_usec
      add :boot_attempts, :bigint, null: false, default: 0
    end
  end

  def down do
    alter table(:jobs) do
      remove :boot_attempts
      remove :boot_deadline_at
    end
  end
end
