defmodule Athanor.Repo.Migrations.UniqueJobAndFailureReasonCheck do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:runners, [:job_id], name: "runners_unique_job_index")

    create constraint(:jobs, :jobs_failure_reason_check,
             check: """
               failure_reason IS NULL OR failure_reason IN ('nonzero_exit', 'timeout', 'runner_lost', 'boot_failure')
             """
           )
  end

  def down do
    drop_if_exists constraint(:jobs, :jobs_failure_reason_check)

    drop_if_exists unique_index(:runners, [:job_id], name: "runners_unique_job_index")
  end
end
