defmodule Athanor.Repo.Migrations.CreatePipelinesAndJobs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:pipelines, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :git_url, :text, null: false
      add :git_ref, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:jobs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :image, :text, null: false
      add :steps, {:array, :text}, null: false, default: []
      add :env, :map, null: false, default: %{}
      add :timeout, :bigint
      add :needs, {:array, :text}, null: false, default: []

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :state, :text, null: false, default: "queued"

      add :pipeline_id,
          references(:pipelines,
            column: :id,
            name: "jobs_pipeline_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:jobs, [:pipeline_id, :name], name: "jobs_unique_name_per_pipeline_index")
  end

  def down do
    drop constraint(:jobs, "jobs_pipeline_id_fkey")

    drop_if_exists unique_index(:jobs, [:pipeline_id, :name],
                     name: "jobs_unique_name_per_pipeline_index"
                   )

    drop table(:jobs)

    drop table(:pipelines)
  end
end
