defmodule Athanor.Repo.Migrations.AddQueuedAt do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:jobs) do
      add :queued_at, :utc_datetime_usec
    end

    # Backfill existing queued rows so they aren't left without a queued_at after
    # the column is added; inserted_at is the best available approximation.
    execute(
      "UPDATE jobs SET queued_at = inserted_at WHERE state = 'queued' AND queued_at IS NULL"
    )
  end

  def down do
    alter table(:jobs) do
      remove :queued_at
    end
  end
end
