defmodule Athanor.Repo.Migrations.AddRunnersAndFailureReason do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:runners, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :boot_token, :text, null: false
      add :boot_token_expires_at, :utc_datetime_usec, null: false
      add :boot_token_used_at, :utc_datetime_usec
      add :session_token, :text
      add :joined_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :job_id,
          references(:jobs,
            column: :id,
            name: "runners_job_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:runners, [:boot_token], name: "runners_unique_boot_token_index")

    alter table(:jobs) do
      add :failure_reason, :text
    end
  end

  def down do
    alter table(:jobs) do
      remove :failure_reason
    end

    drop constraint(:runners, "runners_job_id_fkey")

    drop_if_exists unique_index(:runners, [:boot_token], name: "runners_unique_boot_token_index")

    drop table(:runners)
  end
end
