defmodule Athanor.Repo.Migrations.AddBootDeadlineIndex do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:jobs, [:boot_deadline_at],
             name: "jobs_assigned_boot_deadline_idx",
             where: "state = 'assigned' AND boot_deadline_at IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:jobs, [:boot_deadline_at], name: "jobs_assigned_boot_deadline_idx")
  end
end
