defmodule Athanor.Repo.Migrations.AddRunnerContainerId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:runners) do
      add :container_id, :text
    end
  end

  def down do
    alter table(:runners) do
      remove :container_id
    end
  end
end
